version: "3.8"
services:
  frontend:
    image: ${DOCKER_HUB_USERNAME}/filmfinder-app-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    networks:
      - app-network

  backend:
    image: ${DOCKER_HUB_USERNAME}/filmfinder-app-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
