version: "3.8"
services:
  frontend:
    image: ${DOCKER_HUB_IMG_FRONTEND}
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - app-network

  backend:
    image: ${DOCKER_HUB_IMG_BACKEND}
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
