version: "3.8"
services:
  frontend:
    image: ${DOCKER_USER}/filmfinder-app-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - /home/ubuntu/full-stack/frontend.env
    networks:
      - app-network

  backend:
    image: ${DOCKER_USER}/filmfinder-app-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWOR}
      - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - TOKEN_EXPIRATION=${TOKEN_EXPIRATION}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
