spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

image:
  upload:
    path: /static/img/

jjwt:
  secret: ${TOKEN_SECRET_KEY}
  expiration: ${TOKEN_EXPIRATION}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            config:
              annotation:
                CorsRegistry: DEBUG
            handler:
              CorsFilter: DEBUG
          cors:
            DefaultCorsProcessor: TRACE
