spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

image:
  upload:
    path: /static/img/
  save:
    path: /path/to/save/images/

jjwt:
  secret: J16DvhzB4awhvd6uPWWXIFb4AajaRDT5BhYWrhyqGOJ4
  expiration: 1800000

kobis:
  api:
    key: 775a62fe3322107b4f1a39f257dc7801
    url: http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json