name: Movie Web CI/CD Pipline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Give execution rights on gradlew
        run: chmod +x backend/gradlew
        
      - name: Build with Gradle
        run: |
         cd backend
         ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/didacto-app-dev .
          docker push ${{ secrets.DOCKER_HUB_USER }}/didacto-app-dev

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Frontend Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/didacto-app-dev-frontend -f Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USER }}/didacto-app-dev-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /fullstack/full-stack
            sudo docker-compose pull backend frontend
            sudo docker-compose stop backend frontend
            sudo docker-compose rm -f backend frontend
            sudo docker-compose up -d backend frontend
